### ISSUE TITLE
Creacion de Footer

### ISSUE THREAD

**Issue by mauroschork** [mauroschork/mytinerary-schork-chaban#3]
Crear un footer que sera utilizado por el momento para la pagina de bienvenida
Aun no debe contener demasiada info ya que eso lo agregaremos mas adelante

**Comment by mauroschork** [comment]
COMO desarrollador 
QUIERO crear un footer que contenga la informacion necesaria al dia de la fecha

**Comment by DavidChaban** [comment]
Se crea componentes para footer , se agrega direccion , redes sociales ,mapa y estilos !:)
